environment:
  global:
    PROJECT_SPEC: "digital_rf==2.6.5"
    PACKAGE_NAME: "digital_rf"
    # the following are installed with conda, use conda version spec
    # need same HDF5 version that is bundled with h5py wheel
    HDF5_DEP: "hdf5=1.10.4"
    H5PY_DEP: "h5py>=2.7.1"
    NUMPY_DEP: "numpy=1.9"
    BUILD_DEP: "pkgconfig setuptools wheel"
    # the following are installed with pip, use pip version spec
    TEST_DEP: "pytest"
    # Note: TWINE_USERNAME and TWINE_PASSWORD are set in AppVeyor settings

  matrix:
    - CONDA_INSTALL_LOCN: "C:\\Miniconda"
      CONDA_PY: "27"
      PYTHON_VERSION: "2.7"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      PYTHON_VERSION: "2.7"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda3"
      CONDA_PY: "36"
      PYTHON_VERSION: "3.6"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda3-x64"
      CONDA_PY: "36"
      PYTHON_VERSION: "3.6"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda3"
      CONDA_PY: "37"
      PYTHON_VERSION: "3.7"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda3-x64"
      CONDA_PY: "37"
      PYTHON_VERSION: "3.7"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda3"
      CONDA_PY: "38"
      PYTHON_VERSION: "3.8"
      NUMPY_DEP: "numpy=1.14"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda3-x64"
      CONDA_PY: "38"
      PYTHON_VERSION: "3.8"
      NUMPY_DEP: "numpy=1.14"

matrix:
    fast_finish: true

install:
    # fetch and unpack python sources
    - "pip download --no-deps --no-binary %PACKAGE_NAME% -d dl_tmp %PROJECT_SPEC%"
    - 7z x dl_tmp\* -so | 7z x -si -ttar -oarch_tmp
    - mkdir src
    - for /d %%A in (arch_tmp\*) do (robocopy "%%A" src /MIR /NP) ^& IF %ERRORLEVEL% LEQ 3 exit /B 0

    # set up build environment with conda
    - set CPU_COUNT=2
    - set PYTHONUNBUFFERED=1
    - call "%CONDA_INSTALL_LOCN%\Scripts\activate.bat"
    # add channels
    - conda config --add channels conda-forge
    - conda config --set auto_update_conda false

    # create build environment
    - conda create --yes -n build_env python=%PYTHON_VERSION% conda
    - conda activate build_env
    # update conda
    - conda update --yes --quiet -n root conda
    # needed for building extensions in python 2.7 x64 with cmake
    - conda install --yes --quiet vs2008_express_vc_python_patch
    - call setup_x64
    # info for debugging
    - conda info

    # make sure we have the newest package versions
    - python -m pip install -U pip

    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"

build_script:
    # Install the dependencies of the project.
    - conda install --yes %HDF5_DEP% %NUMPY_DEP% %BUILD_DEP%
    # Build wheel
    - set HDF5_ROOT=%CONDA_PREFIX%\Library
    # add required external libraries to wheel package using setup.py environment variable
    # (not necessary for now since h5py bundles hdf5.dll, since we require
    #  h5py it will use that version)
    #- set DRF_PACKAGE_EXTERNAL_LIBS=%CONDA_PREFIX%\Library\bin\hdf5.dll;%CONDA_PREFIX%\Library\bin\zlib.dll
    # require the specific h5py version that we know works
    - set DRF_H5PY_SPEC=%H5PY_DEP%
    - python -m pip wheel -v -w wheelhouse --no-deps .\src
    - dir wheelhouse

test_script:
    # create test env
    - conda create --yes -n test_env python=%PYTHON_VERSION%
    - conda activate test_env
    - where python
    - python -m pip install "%TEST_DEP%"

    # install from wheel
    - pwsh: ls wheelhouse\*.whl | % { python -m pip install $_ }

    # run the tests
    - pytest --maxfail=10 src

artifacts:
    - path: "wheelhouse\\*"

on_success:
    # Upload wheels to PyPI
    - python -m pip install --upgrade pyOpenSSL
    - python -m pip install twine
    - python -m twine upload --skip-existing wheelhouse\*
